version: '3.3'

services:
  redis:
      image: redis
      restart: always
  nginx:
    restart: always
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - 1337:80
    depends_on:
      - web
  web:
    restart: always
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn --workers=4 website.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  worker:
    restart: always
    build:
      context: ./app
    env_file:
      - ./.env.prod
    command: ["celery", "-A", "website", "worker", "-l", "info"]
  db:
    restart: always
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db


volumes:
  postgres_data:
  static_volume:
  media_volume:

